from collections import OrderedDict

Trans = [
	'ar_arabic', 
	'ar_arabic_clean', 
	'am_sadiq', 
	'ar_jalalayn', 
	'ar_muyassar', 
	'az_mammadaliyev', 
	'az_musayev', 
	'ber_mensur', 
	'bg_theophanov', 
	'bn_bengali', 
	'bn_hoque', 
	'bs_korkut', 
	'bs_mlivo', 
	'cs_hrbek', 
	'cs_nykl', 
	'de_aburida', 
	'de_bubenheim', 
	'de_khoury', 
	'de_zaidan', 
	'dv_divehi', 
	'en_ahmedali', 
	'en_ahmedraza', 
	'en_arberry', 
	'en_daryabadi', 
	'en_hilali', 
	'en_itani', 
	'en_maududi', 
	'en_mubarakpuri', 
	'en_pickthall', 
	'en_qarai', 
	'en_qaribullah', 
	'en_sahih', 
	'en_sarwar', 
	'en_shakir', 
	'en_transliteration', 
	'en_wahiduddin', 
	'en_yusufali', 
	'es_bornez', 
	'es_cortes', 
	'es_garcia', 
	'fa_ansarian', 
	'fa_ayati', 
	'fa_bahrampour', 
	'fa_fooladvand', 
	'fa_ghomshei', 
	'fa_khorramdel', 
	'fa_khorramshahi', 
	'fa_makarem', 
	'fa_moezzi', 
	'fa_mojtabavi', 
	'fa_sadeqi', 
	'fr_hamidullah', 
	'ha_gumi', 
	'hi_farooq', 
	'hi_hindi', 
	'id_indonesian', 
	'id_jalalayn', 
	'id_muntakhab', 
	'it_piccardo', 
	'ja_japanese', 
	'ko_korean', 
	'ku_asan', 
	'ml_abdulhameed', 
	'ml_karakunnu', 
	'ms_basmeih', 
	'nl_keyzer', 
	'nl_leemhuis', 
	'nl_siregar', 
	'no_berg', 
	'pl_bielawskiego', 
	'pt_elhayek', 
	'ro_grigore', 
	'ru_abuadel', 
	'ru_krachkovsky', 
	'ru_kuliev', 
	'ru_kuliev_alsaadi', 
	'ru_muntahab', 
	'ru_osmanov', 
	'ru_porokhova', 
	'ru_sablukov', 
	'sd_amroti', 
	'so_abduh', 
	'sq_ahmeti', 
	'sq_mehdiu', 
	'sq_nahi', 
	'sv_bernstrom', 
	'sw_barwani', 
	'ta_tamil', 
	'tg_ayati', 
	'th_thai', 
	'tr_ates', 
	'tr_bulac', 
	'tr_diyanet', 
	'tr_golpinarli', 
	'tr_ozturk', 
	'tr_transliteration', 
	'tr_vakfi', 
	'tr_yazir', 
	'tr_yildirim', 
	'tr_yuksel', 
	'tt_nugman', 
	'ug_saleh', 
	'ur_ahmedali', 
	'ur_jalandhry', 
	'ur_jawadi', 
	'ur_junagarhi', 
	'ur_kanzuliman', 
	'ur_maududi', 
	'ur_najafi', 
	'ur_qadri', 
	'uz_sodik', 
	'zh_jian', 
	'zh_majian'
]

TransAlias = {
	'ar':  'ar_arabic',
	'arc': 'ar_arabic_clean',
	'am':  'am_sadiq',
	'arj': 'ar_jalalayn',
	'arm': 'ar_muyassar',
	'az':  'az_musayev',#
	'ber': 'ber_mensur',
	'bg':  'bg_theophanov',
	'bn':  'bn_bengali',#
	'bs':  'bs_korkut',#
	'cs':  'cs_hrbek',#
	'de':  'de_aburida',#
	'dv':  'dv_divehi',
	'en':  'en_sahih',
	'tl':  'en_transliteration',
	'es':  'es_bornez',#
	'fa':  'fa_ansarian',#
	'fr':  'fr_hamidullah',
	'ha':  'ha_gumi',
	'hi':  'hi_hindi',#
	'id':  'id_indonesian',#
	'idj': 'id_jalalayn',
	'it':  'it_piccardo',
	'ja':  'ja_japanese',
	'ko':  'ko_korean',
	'ku':  'ku_asan',
	'ml':  'ml_abdulhameed',#
	'ms':  'ms_basmeih',
	'nl':  'nl_keyzer',#
	'no':  'no_berg',
	'pl':  'pl_bielawskiego',
	'pt':  'pt_elhayek',
	'ro':  'ro_grigore',
	'ru':  'ru_kuliev',#
	'rus': 'ru_kuliev_alsaadi',
	'sd':  'sd_amroti',
	'so':  'so_abduh',
	'sq':  'sq_ahmeti',#
	'sv':  'sv_bernstrom',
	'sw':  'sw_barwani',
	'ta':  'ta_tamil',
	'tg':  'tg_ayati',
	'th':  'th_thai',
	'tr':  'tr_ozturk',
	'trtl': 'tr_transliteration',
	'tt':  'tt_nugman',
	'ug':  'ug_saleh',
	'ur':  'ur_junagarhi',
	'uz':  'uz_sodik',
	'zh':  'zh_majian'
}

TransInfo = OrderedDict([
	('ar_arabic_clean', OrderedDict([('name', 'القرآن الكريم'), ('translator', ''), ('language', 'Arabic'), ('last_update', ''), ('source', 'Tanzil.net')])), 
	('ar_arabic', OrderedDict([('name', 'القرآن الكريم'), ('translator', ''), ('language', 'Arabic'), ('last_update', ''), ('source', 'Tanzil.net')])), 
	('am_sadiq', OrderedDict([('name', 'ሳዲቅ & ሳኒ ሐቢብ'), ('translator', 'Muhammed Sadiq and Muhammed Sani Habib'), ('language', 'Amharic '), ('last_update', 'August 3, 2012'), ('source', 'Tanzil.net')])), 
	('ar_jalalayn', OrderedDict([('name', 'تفسير الجلالين'), ('translator', 'Jalal ad-Din al-Mahalli and Jalal ad-Din as-Suyuti'), ('language', 'Arabic'), ('last_update', 'December 1, 2010'), ('source', 'Tanzil.net')])), 
	('ar_muyassar', OrderedDict([('name', 'تفسير المیسر'), ('translator', 'King Fahad Quran Complex'), ('language', 'Arabic'), ('last_update', 'January 7, 2011'), ('source', 'Tanzil.net')])), 
	('az_mammadaliyev', OrderedDict([('name', 'Məmmədəliyev & Bünyadov'), ('translator', 'Vasim Mammadaliyev and Ziya Bunyadov'), ('language', 'Azerbaijani'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('az_musayev', OrderedDict([('name', 'Musayev'), ('translator', 'Alikhan Musayev'), ('language', 'Azerbaijani'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('ber_mensur', OrderedDict([('name', 'At Mensur'), ('translator', 'Ramdane At Mansour'), ('language', 'Amazigh'), ('last_update', 'July 24, 2012'), ('source', 'Tanzil.net')])), 
	('bg_theophanov', OrderedDict([('name', 'Теофанов'), ('translator', 'Tzvetan Theophanov'), ('language', 'Bulgarian'), ('last_update', 'August 12, 2014'), ('source', 'Tanzil.net')])), 
	('bn_bengali', OrderedDict([('name', 'মুহিউদ্দীন খান'), ('translator', 'Muhiuddin Khan'), ('language', 'Bengali'), ('last_update', 'April 30, 2011'), ('source', 'Tanzil.net')])), 
	('bn_hoque', OrderedDict([('name', 'জহুরুল হক'), ('translator', 'Zohurul Hoque'), ('language', 'Bengali'), ('last_update', 'July 19, 2013'), ('source', 'Tanzil.net')])), 
	('bs_korkut', OrderedDict([('name', 'Korkut'), ('translator', 'Besim Korkut'), ('language', 'Bosnian'), ('last_update', 'May 22, 2013'), ('source', 'Tanzil.net')])), 
	('bs_mlivo', OrderedDict([('name', 'Mlivo'), ('translator', 'Mustafa Mlivo'), ('language', 'Bosnian'), ('last_update', 'August 24, 2010'), ('source', 'Tanzil.net')])), 
	('cs_hrbek', OrderedDict([('name', 'Hrbek'), ('translator', 'Preklad I. Hrbek'), ('language', 'Czech'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('cs_nykl', OrderedDict([('name', 'Nykl'), ('translator', 'A. R. Nykl'), ('language', 'Czech'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('de_aburida', OrderedDict([('name', 'Abu Rida'), ('translator', 'Abu Rida Muhammad ibn Ahmad ibn Rassoul'), ('language', 'German'), ('last_update', 'August 19, 2011'), ('source', 'Tanzil.net')])), 
	('de_bubenheim', OrderedDict([('name', 'Bubenheim & Elyas'), ('translator', 'A. S. F. Bubenheim and N. Elyas'), ('language', 'German'), ('last_update', 'July 17, 2011'), ('source', 'Tanzil.net')])), 
	('de_khoury', OrderedDict([('name', 'Khoury'), ('translator', 'Adel Theodor Khoury'), ('language', 'German'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('de_zaidan', OrderedDict([('name', 'Zaidan'), ('translator', 'Amir Zaidan'), ('language', 'German'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('dv_divehi', OrderedDict([('name', 'ދިވެހި'), ('translator', 'Office of the President of Maldives'), ('language', 'Divehi'), ('last_update', 'February 7, 2011'), ('source', 'Tanzil.net')])), 
	('en_ahmedali', OrderedDict([('name', 'Ahmed Ali'), ('translator', 'Ahmed Ali'), ('language', 'English'), ('last_update', 'August 28, 2010'), ('source', 'Tanzil.net')])), 
	('en_ahmedraza', OrderedDict([('name', 'Ahmed Raza Khan'), ('translator', 'Ahmed Raza Khan'), ('language', 'English'), ('last_update', 'July 17, 2011'), ('source', 'Tanzil.net')])), 
	('en_arberry', OrderedDict([('name', 'Arberry'), ('translator', 'A. J. Arberry'), ('language', 'English'), ('last_update', 'July 31, 2011'), ('source', 'Tanzil.net')])), 
	('en_daryabadi', OrderedDict([('name', 'Daryabadi'), ('translator', 'Abdul Majid Daryabadi'), ('language', 'English'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('en_hilali', OrderedDict([('name', 'Hilali & Khan'), ('translator', 'Muhammad Taqi-ud-Din al-Hilali and Muhammad Muhsin Khan'), ('language', 'English'), ('last_update', 'December 13, 2010'), ('source', 'Tanzil.net')])), 
	('en_itani', OrderedDict([('name', 'Itani'), ('translator', 'Talal Itani'), ('language', 'English'), ('last_update', 'July 19, 2013'), ('source', 'Tanzil.net')])), 
	('en_maududi', OrderedDict([('name', 'Maududi'), ('translator', 'Abul Ala Maududi'), ('language', 'English'), ('last_update', 'May 10, 2011'), ('source', 'Tanzil.net')])), 
	('en_mubarakpuri', OrderedDict([('name', 'Mubarakpuri'), ('translator', 'Safi-ur-Rahman al-Mubarakpuri'), ('language', 'English'), ('last_update', 'June 20, 2015'), ('source', 'Tanzil.net')])), 
	('en_pickthall', OrderedDict([('name', 'Pickthall'), ('translator', 'Mohammed Marmaduke William Pickthall'), ('language', 'English'), ('last_update', 'September 4, 2010'), ('source', 'Tanzil.net')])), 
	('en_qarai', OrderedDict([('name', 'Qarai'), ('translator', 'Ali Quli Qarai'), ('language', 'English'), ('last_update', 'July 16, 2013'), ('source', 'Tanzil.net')])), 
	('en_qaribullah', OrderedDict([('name', 'Qaribullah & Darwish'), ('translator', 'Hasan al-Fatih Qaribullah and Ahmad Darwish'), ('language', 'English'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('en_sahih', OrderedDict([('name', 'Saheeh International'), ('translator', 'Saheeh International'), ('language', 'English'), ('last_update', 'April 24, 2011'), ('source', 'Tanzil.net')])), 
	('en_sarwar', OrderedDict([('name', 'Sarwar'), ('translator', 'Muhammad Sarwar'), ('language', 'English'), ('last_update', 'July 30, 2012'), ('source', 'Tanzil.net')])), 
	('en_shakir', OrderedDict([('name', 'Shakir'), ('translator', 'Mohammad Habib Shakir'), ('language', 'English'), ('last_update', 'June 22, 2010'), ('source', 'Tanzil.net')])), 
	('en_transliteration', OrderedDict([('name', 'Transliteration'), ('translator', 'English Transliteration'), ('language', 'English'), ('last_update', 'September 6, 2010'), ('source', 'Tanzil.net')])), 
	('en_wahiduddin', OrderedDict([('name', 'Wahiduddin Khan'), ('translator', 'Wahiduddin Khan'), ('language', 'English'), ('last_update', 'August 25, 2011'), ('source', 'Tanzil.net')])), 
	('en_yusufali', OrderedDict([('name', 'Yusuf Ali'), ('translator', 'Abdullah Yusuf Ali'), ('language', 'English'), ('last_update', 'May 10, 2013'), ('source', 'Tanzil.net')])), 
	('es_bornez', OrderedDict([('name', 'Bornez'), ('translator', 'Raúl González Bórnez'), ('language', 'Spanish'), ('last_update', 'July 15, 2014'), ('source', 'Tanzil.net')])), 
	('es_cortes', OrderedDict([('name', 'Cortes'), ('translator', 'Julio Cortes '), ('language', 'Spanish'), ('last_update', 'August 12, 2014'), ('source', 'Tanzil.net')])), 
	('es_garcia', OrderedDict([('name', 'Garcia'), ('translator', 'Muhammad Isa García'), ('language', 'Spanish'), ('last_update', 'July 15, 2014'), ('source', 'Tanzil.net')])), 
	('fa_ansarian', OrderedDict([('name', 'انصاریان'), ('translator', 'Hussain Ansarian'), ('language', 'Persian'), ('last_update', 'July 6, 2011'), ('source', 'Tanzil.net')])), 
	('fa_ayati', OrderedDict([('name', 'آیتی'), ('translator', 'AbdolMohammad Ayati'), ('language', 'Persian'), ('last_update', 'August 1, 2012'), ('source', 'Tanzil.net')])), 
	('fa_bahrampour', OrderedDict([('name', 'بهرام پور'), ('translator', 'Abolfazl Bahrampour'), ('language', 'Persian'), ('last_update', 'November 29, 2013'), ('source', 'Tanzil.net')])), 
	('fa_fooladvand', OrderedDict([('name', 'فولادوند'), ('translator', 'Mohammad Mahdi Fooladvand'), ('language', 'Persian'), ('last_update', 'June 18, 2011'), ('source', 'Tanzil.net')])), 
	('fa_ghomshei', OrderedDict([('name', 'الهی قمشه‌ای'), ('translator', 'Mahdi Elahi Ghomshei'), ('language', 'Persian'), ('last_update', 'July 17, 2011'), ('source', 'Tanzil.net')])), 
	('fa_khorramdel', OrderedDict([('name', 'خرمدل'), ('translator', 'Mostafa Khorramdel'), ('language', 'Persian'), ('last_update', 'March 19, 2011'), ('source', 'Tanzil.net')])), 
	('fa_khorramshahi', OrderedDict([('name', 'خرمشاهی'), ('translator', "Baha'oddin Khorramshahi"), ('language', 'Persian'), ('last_update', 'July 27, 2012'), ('source', 'Tanzil.net')])), 
	('fa_makarem', OrderedDict([('name', 'مکارم شیرازی'), ('translator', 'Naser Makarem Shirazi'), ('language', 'Persian'), ('last_update', 'January 22, 2014'), ('source', 'Tanzil.net')])), 
	('fa_moezzi', OrderedDict([('name', 'معزی'), ('translator', 'Mohammad Kazem Moezzi'), ('language', 'Persian'), ('last_update', 'August 24, 2010'), ('source', 'Tanzil.net')])), 
	('fa_mojtabavi', OrderedDict([('name', 'مجتبوی'), ('translator', 'Sayyed Jalaloddin Mojtabavi'), ('language', 'Persian'), ('last_update', 'April 16, 2012'), ('source', 'Tanzil.net')])), 
	('fa_sadeqi', OrderedDict([('name', 'صادقی تهرانی'), ('translator', 'Mohammad Sadeqi Tehrani'), ('language', 'Persian'), ('last_update', 'August 1, 2011'), ('source', 'Tanzil.net')])), 
	('fr_hamidullah', OrderedDict([('name', 'Hamidullah'), ('translator', 'Muhammad Hamidullah'), ('language', 'French'), ('last_update', 'July 18, 2011'), ('source', 'Tanzil.net')])), 
	('ha_gumi', OrderedDict([('name', 'Gumi'), ('translator', 'Abubakar Mahmoud Gumi'), ('language', 'Hausa'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('hi_farooq', OrderedDict([('name', 'फ़ारूक़ ख़ान & अहमद'), ('translator', 'Muhammad Farooq Khan and Muhammad Ahmed  '), ('language', 'Hindi'), ('last_update', 'March 18, 2011'), ('source', 'Tanzil.net')])), 
	('hi_hindi', OrderedDict([('name', 'फ़ारूक़ ख़ान & नदवी'), ('translator', 'Suhel Farooq Khan and Saifur Rahman Nadwi'), ('language', 'Hindi'), ('last_update', 'January 12, 2011'), ('source', 'Tanzil.net')])), 
	('id_indonesian', OrderedDict([('name', 'Bahasa Indonesia'), ('translator', 'Indonesian Ministry of Religious Affairs'), ('language', 'Indonesian'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('id_jalalayn', OrderedDict([('name', 'Tafsir Jalalayn'), ('translator', 'Jalal ad-Din al-Mahalli and Jalal ad-Din as-Suyuti'), ('language', 'Indonesian'), ('last_update', 'July 27, 2012'), ('source', 'Tanzil.net')])), 
	('id_muntakhab', OrderedDict([('name', 'Quraish Shihab'), ('translator', 'Muhammad Quraish Shihab et al.'), ('language', 'Indonesian'), ('last_update', 'April 28, 2011'), ('source', 'Tanzil.net')])), 
	('it_piccardo', OrderedDict([('name', 'Piccardo'), ('translator', 'Hamza Roberto Piccardo'), ('language', 'Italian'), ('last_update', 'January 2, 2011'), ('source', 'Tanzil.net')])), 
	('ja_japanese', OrderedDict([('name', 'Japanese'), ('translator', 'Unknown'), ('language', 'Japanese'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('ko_korean', OrderedDict([('name', 'Korean'), ('translator', 'Unknown'), ('language', 'Korean'), ('last_update', 'July 15, 2011'), ('source', 'Tanzil.net')])), 
	('ku_asan', OrderedDict([('name', 'ته‌فسیری ئاسان'), ('translator', 'Burhan Muhammad-Amin'), ('language', 'Kurdish'), ('last_update', 'September 14, 2010'), ('source', 'Tanzil.net')])), 
	('ml_abdulhameed', OrderedDict([('name', 'അബ്ദുല്‍ ഹമീദ് & പറപ്പൂര്‍'), ('translator', 'Cheriyamundam Abdul Hameed and Kunhi Mohammed Parappoor'), ('language', 'Malayalam'), ('last_update', 'April 2, 2012'), ('source', 'Tanzil.net')])), 
	('ml_karakunnu', OrderedDict([('name', 'കാരകുന്ന് & എളയാവൂര്'), ('translator', 'Muhammad Karakunnu and Vanidas Elayavoor'), ('language', 'Malayalam'), ('last_update', 'April 2, 2012'), ('source', 'Tanzil.net')])), 
	('ms_basmeih', OrderedDict([('name', 'Basmeih'), ('translator', 'Abdullah Muhammad Basmeih'), ('language', 'Malay'), ('last_update', 'September 7, 2012'), ('source', 'Tanzil.net')])), 
	('nl_keyzer', OrderedDict([('name', 'Keyzer'), ('translator', 'Salomo Keyzer '), ('language', 'Dutch'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('nl_leemhuis', OrderedDict([('name', 'Leemhuis'), ('translator', 'Fred Leemhuis'), ('language', 'Dutch'), ('last_update', 'August 5, 2012'), ('source', 'Tanzil.net')])), 
	('nl_siregar', OrderedDict([('name', 'Siregar'), ('translator', 'Sofian S. Siregar'), ('language', 'Dutch'), ('last_update', 'August 5, 2012'), ('source', 'Tanzil.net')])), 
	('no_berg', OrderedDict([('name', 'Einar Berg'), ('translator', 'Einar Berg'), ('language', 'Norwegian'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('pl_bielawskiego', OrderedDict([('name', 'Bielawskiego'), ('translator', 'Józefa Bielawskiego'), ('language', 'Polish'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('pt_elhayek', OrderedDict([('name', 'El-Hayek'), ('translator', 'Samir El-Hayek '), ('language', 'Portuguese'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('ro_grigore', OrderedDict([('name', 'Grigore'), ('translator', 'George Grigore'), ('language', 'Romanian'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('ru_abuadel', OrderedDict([('name', 'Абу Адель'), ('translator', 'Abu Adel'), ('language', 'Russian'), ('last_update', 'September 15, 2010'), ('source', 'Tanzil.net')])), 
	('ru_krachkovsky', OrderedDict([('name', 'Крачковский'), ('translator', 'Ignaty Yulianovich Krachkovsky'), ('language', 'Russian'), ('last_update', 'September 20, 2010'), ('source', 'Tanzil.net')])), 
	('ru_kuliev', OrderedDict([('name', 'Кулиев'), ('translator', 'Elmir Kuliev'), ('language', 'Russian'), ('last_update', 'May 29, 2011'), ('source', 'Tanzil.net')])), 
	('ru_kuliev_alsaadi', OrderedDict([('name', 'Кулиев + ас-Саади'), ('translator', "Elmir Kuliev (with Abd ar-Rahman as-Saadi's commentaries)"), ('language', 'Russian'), ('last_update', 'October 4, 2010'), ('source', 'Tanzil.net')])), 
	('ru_muntahab', OrderedDict([('name', 'Аль-Мунтахаб'), ('translator', 'Ministry of Awqaf, Egypt'), ('language', 'Russian'), ('last_update', 'May 29, 2011'), ('source', 'Tanzil.net')])), 
	('ru_osmanov', OrderedDict([('name', 'Османов'), ('translator', 'Magomed-Nuri Osmanovich Osmanov'), ('language', 'Russian'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('ru_porokhova', OrderedDict([('name', 'Порохова'), ('translator', 'V. Porokhova'), ('language', 'Russian'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('ru_sablukov', OrderedDict([('name', 'Саблуков'), ('translator', 'Gordy Semyonovich Sablukov'), ('language', 'Russian'), ('last_update', 'October 4, 2010'), ('source', 'Tanzil.net')])), 
	('sd_amroti', OrderedDict([('name', 'امروٽي'), ('translator', 'Taj Mehmood Amroti'), ('language', 'Sindhi'), ('last_update', 'April 9, 2012'), ('source', 'Tanzil.net')])), 
	('so_abduh', OrderedDict([('name', 'Abduh'), ('translator', 'Mahmud Muhammad Abduh'), ('language', 'Somali'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('sq_ahmeti', OrderedDict([('name', 'Sherif Ahmeti'), ('translator', 'Sherif Ahmeti'), ('language', 'Albanian'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('sq_mehdiu', OrderedDict([('name', 'Feti Mehdiu'), ('translator', 'Feti Mehdiu'), ('language', 'Albanian'), ('last_update', 'December 1, 2010'), ('source', 'Tanzil.net')])), 
	('sq_nahi', OrderedDict([('name', 'Efendi Nahi'), ('translator', 'Hasan Efendi Nahi'), ('language', 'Albanian'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('sv_bernstrom', OrderedDict([('name', 'Bernström'), ('translator', 'Knut Bernström'), ('language', 'Swedish'), ('last_update', 'July 30, 2012'), ('source', 'Tanzil.net')])), 
	('sw_barwani', OrderedDict([('name', 'Al-Barwani'), ('translator', 'Ali Muhsin Al-Barwani'), ('language', 'Swahili'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('ta_tamil', OrderedDict([('name', 'ஜான் டிரஸ்ட்'), ('translator', 'Jan Turst Foundation'), ('language', 'Tamil'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('tg_ayati', OrderedDict([('name', 'Оятӣ'), ('translator', 'AbdolMohammad Ayati'), ('language', 'Tajik'), ('last_update', 'August 4, 2010'), ('source', 'Tanzil.net')])), 
	('th_thai', OrderedDict([('name', 'ภาษาไทย'), ('translator', 'King Fahad Quran Complex'), ('language', 'Thai'), ('last_update', 'October 10, 2011'), ('source', 'Tanzil.net')])), 
	('tr_ates', OrderedDict([('name', 'Süleyman Ateş'), ('translator', 'Suleyman Ates'), ('language', 'Turkish'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('tr_bulac', OrderedDict([('name', 'Alİ Bulaç'), ('translator', 'Alİ Bulaç'), ('language', 'Turkish'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('tr_diyanet', OrderedDict([('name', 'Diyanet İşleri'), ('translator', 'Diyanet Isleri'), ('language', 'Turkish'), ('last_update', 'December 27, 2011'), ('source', 'Tanzil.net')])), 
	('tr_golpinarli', OrderedDict([('name', 'Abdulbakî Gölpınarlı'), ('translator', 'Abdulbaki Golpinarli'), ('language', 'Turkish'), ('last_update', 'September 14, 2010'), ('source', 'Tanzil.net')])), 
	('tr_ozturk', OrderedDict([('name', 'Öztürk'), ('translator', 'Yasar Nuri Ozturk'), ('language', 'Turkish'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('tr_transliteration', OrderedDict([('name', 'Çeviriyazı'), ('translator', 'Muhammet Abay'), ('language', 'Turkish'), ('last_update', 'September 15, 2010'), ('source', 'Tanzil.net')])), 
	('tr_vakfi', OrderedDict([('name', 'Diyanet Vakfı'), ('translator', 'Diyanet Vakfi'), ('language', 'Turkish'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('tr_yazir', OrderedDict([('name', 'Elmalılı Hamdi Yazır'), ('translator', 'Elmalili Hamdi Yazir'), ('language', 'Turkish'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('tr_yildirim', OrderedDict([('name', 'Suat Yıldırım'), ('translator', 'Suat Yildirim'), ('language', 'Turkish'), ('last_update', 'September 14, 2010'), ('source', 'Tanzil.net')])), 
	('tr_yuksel', OrderedDict([('name', 'Edip Yüksel'), ('translator', 'Edip Yüksel'), ('language', 'Turkish'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('tt_nugman', OrderedDict([('name', 'Yakub Ibn Nugman'), ('translator', 'Yakub Ibn Nugman'), ('language', 'Tatar'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('ug_saleh', OrderedDict([('name', 'محمد صالح'), ('translator', 'Muhammad Saleh'), ('language', 'Uyghur'), ('last_update', 'June 4, 2010'), ('source', 'Tanzil.net')])), 
	('ur_ahmedali', OrderedDict([('name', 'احمد علی'), ('translator', 'Ahmed Ali'), ('language', 'Urdu'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('ur_jalandhry', OrderedDict([('name', 'جالندہری'), ('translator', 'Fateh Muhammad Jalandhry'), ('language', 'Urdu'), ('last_update', 'December 24, 2010'), ('source', 'Tanzil.net')])), 
	('ur_jawadi', OrderedDict([('name', 'علامہ جوادی'), ('translator', 'Syed Zeeshan Haider Jawadi'), ('language', 'Urdu'), ('last_update', 'December 24, 2010'), ('source', 'Tanzil.net')])), 
	('ur_junagarhi', OrderedDict([('name', 'محمد جوناگڑھی'), ('translator', 'Muhammad Junagarhi'), ('language', 'Urdu'), ('last_update', 'April 25, 2011'), ('source', 'Tanzil.net')])), 
	('ur_kanzuliman', OrderedDict([('name', 'احمد رضا خان'), ('translator', 'Ahmed Raza Khan'), ('language', 'Urdu'), ('last_update', 'March 17, 2011'), ('source', 'Tanzil.net')])), 
	('ur_maududi', OrderedDict([('name', 'ابوالاعلی مودودی'), ('translator', "Abul A'ala Maududi"), ('language', 'Urdu'), ('last_update', 'November 15, 2010'), ('source', 'Tanzil.net')])), 
	('ur_najafi', OrderedDict([('name', 'محمد حسین نجفی'), ('translator', 'Ayatollah Muhammad Hussain Najafi '), ('language', 'Urdu'), ('last_update', 'August 19, 2011'), ('source', 'Tanzil.net')])), 
	('ur_qadri', OrderedDict([('name', 'طاہر القادری'), ('translator', 'Tahir ul Qadri'), ('language', 'Urdu'), ('last_update', 'August 16, 2010'), ('source', 'Tanzil.net')])), 
	('uz_sodik', OrderedDict([('name', 'Мухаммад Содик'), ('translator', 'Muhammad Sodik Muhammad Yusuf'), ('language', 'Uzbek'), ('last_update', 'July 17, 2011'), ('source', 'Tanzil.net')])), 
	('zh_jian', OrderedDict([('name', 'Ma Jian'), ('translator', 'Ma Jian'), ('language', 'Chinese'), ('last_update', 'March 13, 2011'), ('source', 'Tanzil.net')])), 
	('zh_majian', OrderedDict([('name', 'Ma Jian (Traditional)'), ('translator', 'Ma Jian'), ('language', 'Chinese'), ('last_update', 'January 7, 2011'), ('source', 'Tanzil.net')]))
])

MetaData = [
	[],
    [0,    7,   5,   1,  'الفاتحة',   "Al-Faatiha",     'The Opening',                'Meccan'],
	[7,    286, 87,  40, 'البقرة',    "Al-Baqara",      'The Cow',                    'Medinan'],
	[293,  200, 89,  20, 'آل عمران',  "Aal-i-Imraan",   'The Family of Imraan',       'Medinan'],
	[493,  176, 92,  24, 'النساء',    "An-Nisaa",       'The Women',                  'Medinan'],
	[669,  120, 112, 16, 'المائدة',   "Al-Maaida",      'The Table',                  'Medinan'],
	[789,  165, 55,  20, 'الأنعام',    "Al-An'aam",      'The Cattle',                 'Meccan'],
	[954,  206, 39,  24, 'الأعراف',    "Al-A'raaf",      'The Heights',                'Meccan'],
	[1160, 75,  88,  10, 'الأنفال',    "Al-Anfaal",      'The Spoils of War',          'Medinan'],
	[1235, 129, 113, 16, 'التوبة',    "At-Tawba",       'The Repentance',             'Medinan'],
	[1364, 109, 51,  11, 'يونس',      "Yunus",          'Jonas',                      'Meccan'],
	[1473, 123, 52,  10, 'هود',       "Hud",            'Hud',                        'Meccan'],
	[1596, 111, 53,  12, 'يوسف',      "Yusuf",          'Joseph',                     'Meccan'],
	[1707, 43,  96,  6,  'الرعد',     "Ar-Ra'd",        'The Thunder',                'Medinan'],
	[1750, 52,  72,  7,  'ابراهيم',   "Ibrahim",        'Abraham',                    'Meccan'],
	[1802, 99,  54,  6,  'الحجر',     "Al-Hijr",        'The Rock',                   'Meccan'],
	[1901, 128, 70,  16, 'النحل',     "An-Nahl",        'The Bee',                    'Meccan'],
	[2029, 111, 50,  12, 'الإسراء',    "Al-Israa",       'The Night Journey',          'Meccan'],
	[2140, 110, 69,  12, 'الكهف',     "Al-Kahf",        'The Cave',                   'Meccan'],
	[2250, 98,  44,  6,  'مريم',      "Maryam",         'Mary',                       'Meccan'],
	[2348, 135, 45,  8,  'طه',        "Taa-Haa",        'Taa-Haa',                    'Meccan'],
	[2483, 112, 73,  7,  'الأنبياء',   "Al-Anbiyaa",     'The Prophets',               'Meccan'],
	[2595, 78,  103, 10, 'الحج',      "Al-Hajj",        'The Pilgrimage',             'Medinan'],
	[2673, 118, 74,  6,  'المؤمنون',  "Al-Muminoon",    'The Believers',              'Meccan'],
	[2791, 64,  102, 9,  'النور',     "An-Noor",        'The Light',                  'Medinan'],
	[2855, 77,  42,  6,  'الفرقان',   "Al-Furqaan",     'The Criterion',              'Meccan'],
	[2932, 227, 47,  11, 'الشعراء',   "Ash-Shu'araa",   'The Poets',                  'Meccan'],
	[3159, 93,  48,  7,  'النمل',     "An-Naml",        'The Ant',                    'Meccan'],
	[3252, 88,  49,  8,  'القصص',     "Al-Qasas",       'The Stories',                'Meccan'],
	[3340, 69,  85,  7,  'العنكبوت',  "Al-Ankaboot",    'The Spider',                 'Meccan'],
	[3409, 60,  84,  6,  'الروم',     "Ar-Room",        'The Romans',                 'Meccan'],
	[3469, 34,  57,  3,  'لقمان',     "Luqman",         'Luqman',                     'Meccan'],
	[3503, 30,  75,  3,  'السجدة',    "As-Sajda",       'The Prostration',            'Meccan'],
	[3533, 73,  90,  9,  'الأحزاب',    "Al-Ahzaab",      'The Clans',                  'Medinan'],
	[3606, 54,  58,  6,  'سبإ',       "Saba",           'Sheba',                      'Meccan'],
	[3660, 45,  43,  5,  'فاطر',      "Faatir",         'The Originator',             'Meccan'],
	[3705, 83,  41,  5,  'يس',        "Yaseen",         'Yaseen',                     'Meccan'],
	[3788, 182, 56,  5,  'الصافات',   "As-Saaffaat",    'Those drawn up in Ranks',    'Meccan'],
	[3970, 88,  38,  5,  'ص',         "Saad",           'The letter Saad',            'Meccan'],
	[4058, 75,  59,  8,  'الزمر',     "Az-Zumar",       'The Groups',                 'Meccan'],
	[4133, 85,  60,  9,  'غافر',      "Al-Ghaafir",     'The Forgiver',               'Meccan'],
	[4218, 54,  61,  6,  'فصلت',      "Fussilat",       'Explained in detail',        'Meccan'],
	[4272, 53,  62,  5,  'الشورى',    "Ash-Shura",      'Consultation',               'Meccan'],
	[4325, 89,  63,  7,  'الزخرف',    "Az-Zukhruf",     'Ornaments of gold',          'Meccan'],
	[4414, 59,  64,  3,  'الدخان',    "Ad-Dukhaan",     'The Smoke',                  'Meccan'],
	[4473, 37,  65,  4,  'الجاثية',   "Al-Jaathiya",    'Crouching',                  'Meccan'],
	[4510, 35,  66,  4,  'الأحقاف',    "Al-Ahqaf",       'The Dunes',                  'Meccan'],
	[4545, 38,  95,  4,  'محمد',      "Muhammad",       'Muhammad',                   'Medinan'],
	[4583, 29,  111, 4,  'الفتح',     "Al-Fath",        'The Victory',                'Medinan'],
	[4612, 18,  106, 2,  'الحجرات',   "Al-Hujuraat",    'The Inner Apartments',       'Medinan'],
	[4630, 45,  34,  3,  'ق',         "Qaaf",           'The letter Qaaf',            'Meccan'],
	[4675, 60,  67,  3,  'الذاريات',  "Adh-Dhaariyat",  'The Winnowing Winds',        'Meccan'],
	[4735, 49,  76,  2,  'الطور',     "At-Tur",         'The Mount',                  'Meccan'],
	[4784, 62,  23,  3,  'النجم',     "An-Najm",        'The Star',                   'Meccan'],
	[4846, 55,  37,  3,  'القمر',     "Al-Qamar",       'The Moon',                   'Meccan'],
	[4901, 78,  97,  3,  'الرحمن',    "Ar-Rahmaan",     'The Beneficent',             'Medinan'],
	[4979, 96,  46,  3,  'الواقعة',   "Al-Waaqia",      'The Inevitable',             'Meccan'],
	[5075, 29,  94,  4,  'الحديد',    "Al-Hadid",       'The Iron',                   'Medinan'],
	[5104, 22,  105, 3,  'المجادلة',  "Al-Mujaadila",   'The Pleading Woman',         'Medinan'],
	[5126, 24,  101, 3,  'الحشر',     "Al-Hashr",       'The Exile',                  'Medinan'],
	[5150, 13,  91,  2,  'الممتحنة',  "Al-Mumtahana",   'She that is to be examined', 'Medinan'],
	[5163, 14,  109, 2,  'الصف',      "As-Saff",        'The Ranks',                  'Medinan'],
	[5177, 11,  110, 2,  'الجمعة',    "Al-Jumu'a",      'Friday',                     'Medinan'],
	[5188, 11,  104, 2,  'المنافقون', "Al-Munaafiqoon", 'The Hypocrites',             'Medinan'],
	[5199, 18,  108, 2,  'التغابن',   "At-Taghaabun",   'Mutual Disillusion',         'Medinan'],
	[5217, 12,  99,  2,  'الطلاق',     "At-Talaaq",      'Divorce',                    'Medinan'],
	[5229, 12,  107, 2,  'التحريم',   "At-Tahrim",      'The Prohibition',            'Medinan'],
	[5241, 30,  77,  2,  'الملك',     "Al-Mulk",        'The Sovereignty',            'Meccan'],
	[5271, 52,  2,   2,  'القلم',     "Al-Qalam",       'The Pen',                    'Meccan'],
	[5323, 52,  78,  2,  'الحاقة',    "Al-Haaqqa",      'The Reality',                'Meccan'],
	[5375, 44,  79,  2,  'المعارج',   "Al-Ma'aarij",    'The Ascending Stairways',    'Meccan'],
	[5419, 28,  71,  2,  'نوح',       "Nooh",           'Noah',                       'Meccan'],
	[5447, 28,  40,  2,  'الجن',      "Al-Jinn",        'The Jinn',                   'Meccan'],
	[5475, 20,  3,   2,  'المزمل',    "Al-Muzzammil",   'The Enshrouded One',         'Meccan'],
	[5495, 56,  4,   2,  'المدثر',    "Al-Muddaththir", 'The Cloaked One',            'Meccan'],
	[5551, 40,  31,  2,  'القيامة',   "Al-Qiyaama",     'The Resurrection',           'Meccan'],
	[5591, 31,  98,  2,  'الانسان',    "Al-Insaan",      'Man',                        'Medinan'],
	[5622, 50,  33,  2,  'المرسلات',   "Al-Mursalaat",   'The Emissaries',             'Meccan'],
	[5672, 40,  80,  2,  'النبإ',     "An-Naba",        'The Announcement',           'Meccan'],
	[5712, 46,  81,  2,  'النازعات',  "An-Naazi'aat",   'Those who drag forth',       'Meccan'],
	[5758, 42,  24,  1,  'عبس',       "Abasa",          'He frowned',                 'Meccan'],
	[5800, 29,  7,   1,  'التكوير',   "At-Takwir",      'The Overthrowing',           'Meccan'],
	[5829, 19,  82,  1,  'الإنفطار',   "Al-Infitaar",    'The Cleaving',               'Meccan'],
	[5848, 36,  86,  1,  'المطففين',  "Al-Mutaffifin",  'Defrauding',                 'Meccan'],
	[5884, 25,  83,  1,  'الإنشقاق',   "Al-Inshiqaaq",   'The Splitting Open',         'Meccan'],
	[5909, 22,  27,  1,  'البروج',    "Al-Burooj",      'The Constellations',         'Meccan'],
	[5931, 17,  36,  1,  'الطارق',    "At-Taariq",      'The Morning Star',           'Meccan'],
	[5948, 19,  8,   1,  'الأعلى',     "Al-A'laa",       'The Most High',              'Meccan'],
	[5967, 26,  68,  1,  'الغاشية',   "Al-Ghaashiya",   'The Overwhelming',           'Meccan'],
	[5993, 30,  10,  1,  'الفجر',     "Al-Fajr",        'The Dawn',                   'Meccan'],
	[6023, 20,  35,  1,  'البلد',     "Al-Balad",       'The City',                   'Meccan'],
	[6043, 15,  26,  1,  'الشمس',     "Ash-Shams",      'The Sun',                    'Meccan'],
	[6058, 21,  9,   1,  'الليل',     "Al-Lail",        'The Night',                  'Meccan'],
	[6079, 11,  11,  1,  'الضحى',     "Ad-Dhuhaa",      'The Morning Hours',          'Meccan'],
	[6090, 8,   12,  1,  'الشرح',     "Ash-Sharh",      'The Consolation',            'Meccan'],
	[6098, 8,   28,  1,  'التين',     "At-Tin",         'The Fig',                    'Meccan'],
	[6106, 19,  1,   1,  'العلق',     "Al-Alaq",        'The Clot',                   'Meccan'],
	[6125, 5,   25,  1,  'القدر',     "Al-Qadr",        'The Power, Fate',            'Meccan'],
	[6130, 8,   100, 1,  'البينة',    "Al-Bayyina",     'The Evidence',               'Medinan'],
	[6138, 8,   93,  1,  'الزلزلة',   "Az-Zalzala",     'The Earthquake',             'Medinan'],
	[6146, 11,  14,  1,  'العاديات',  "Al-Aadiyaat",    'The Chargers',               'Meccan'],
	[6157, 11,  30,  1,  'القارعة',   "Al-Qaari'a",     'The Calamity',               'Meccan'],
	[6168, 8,   16,  1,  'التكاثر',   "At-Takaathur",   'Competition',                'Meccan'],
	[6176, 3,   13,  1,  'العصر',     "Al-Asr",         'The Declining Day, Epoch',   'Meccan'],
	[6179, 9,   32,  1,  'الهمزة',    "Al-Humaza",      'The Traducer',               'Meccan'],
	[6188, 5,   19,  1,  'الفيل',     "Al-Fil",         'The Elephant',               'Meccan'],
	[6193, 4,   29,  1,  'قريش',      "Quraish",        'Quraysh',                    'Meccan'],
	[6197, 7,   17,  1,  'الماعون',   "Al-Maa'un",      'Almsgiving',                 'Meccan'],
	[6204, 3,   15,  1,  'الكوثر',    "Al-Kawthar",     'Abundance',                  'Meccan'],
	[6207, 6,   18,  1,  'الكافرون',  "Al-Kaafiroon",   'The Disbelievers',           'Meccan'],
	[6213, 3,   114, 1,  'النصر',     "An-Nasr",        'Divine Support',             'Medinan'],
	[6216, 5,   6,   1,  'المسد',     "Al-Masad",       'The Palm Fibre',             'Meccan'],
	[6221, 4,   22,  1,  'الإخلاص',     "Al-Ikhlaas",     'Sincerity',                  'Meccan'],
	[6225, 5,   20,  1,  'الفلق',     "Al-Falaq",       'The Dawn',                   'Meccan'],
	[6230, 6,   21,  1,  'الناس',     "An-Naas",        'Mankind',                    'Meccan']
]
